### ISSUE TITLE
control abstraction with errors

### ISSUE THREAD

**Issue by aclaiman** [LGoodacre/context-sequencer#2]
Hi!
I´m using pd vanilla 0.48.1 on windows 7 (on 2 machines one 32bits and other 64bits. On both of them the same error).
The control abstraction don´t load all the gui and have a list of errors in the console.
`array: couldn't find named array '1003-IDshare'
text sequence: line number 0 out of range
text sequence: line number 0 out of range
1004-1-1-off: no such object
1004-1-2-off: no such object
1004-1-3-off: no such object
1004-1-4-off: no such object
1004-1-5-off: no such object
1004-1-6-off: no such object
1004-1-7-off: no such object
1004-1-8-off: no such object
1004-1-1-s: no such object
1004-1-2-s: no such object
1004-1-3-s: no such object
1004-1-4-s: no such object
1004-1-5-s: no such object
1004-1-6-s: no such object
1004-1-7-s: no such object
1004-1-8-s: no such object
1004-1-1-dollarz: no such object
1004-1-2-dollarz: no such object
1004-1-3-dollarz: no such object
1004-1-4-dollarz: no such object
1004-1-5-dollarz: no such object
1004-1-6-dollarz: no such object
1004-1-7-dollarz: no such object
1004-1-8-dollarz: no such object
1004-1-1-off: no such object
1004-1-2-off: no such object
1004-1-3-off: no such object
1004-1-4-off: no such object
1004-1-5-off: no such object
1004-1-6-off: no such object
1004-1-7-off: no such object
1004-1-8-off: no such object
1004-1-1-s: no such object
1004-1-2-s: no such object
1004-1-3-s: no such object
1004-1-4-s: no such object
1004-1-5-s: no such object
1004-1-6-s: no such object
1004-1-7-s: no such object
1004-1-8-s: no such object
1004-1-1-dollarz: no such object
1004-1-2-dollarz: no such object
1004-1-3-dollarz: no such object
1004-1-4-dollarz: no such object
1004-1-5-dollarz: no such object
1004-1-6-dollarz: no such object
1004-1-7-dollarz: no such object
1004-1-8-dollarz: no such object
1004-2-1-off: no such object
1004-2-2-off: no such object
1004-2-3-off: no such object
1004-2-4-off: no such object
1004-2-5-off: no such object
1004-2-6-off: no such object
1004-2-7-off: no such object
1004-2-8-off: no such object
1004-2-1-s: no such object
1004-2-2-s: no such object
1004-2-3-s: no such object
1004-2-4-s: no such object
1004-2-5-s: no such object
1004-2-6-s: no such object
1004-2-7-s: no such object
1004-2-8-s: no such object
1004-2-1-dollarz: no such object
1004-2-2-dollarz: no such object
1004-2-3-dollarz: no such object
1004-2-4-dollarz: no such object
1004-2-5-dollarz: no such object
1004-2-6-dollarz: no such object
1004-2-7-dollarz: no such object
1004-2-8-dollarz: no such object
1004-2-1-off: no such object
1004-2-2-off: no such object
1004-2-3-off: no such object
1004-2-4-off: no such object
1004-2-5-off: no such object
1004-2-6-off: no such object
1004-2-7-off: no such object
1004-2-8-off: no such object
1004-2-1-s: no such object
1004-2-2-s: no such object
1004-2-3-s: no such object
1004-2-4-s: no such object
1004-2-5-s: no such object
1004-2-6-s: no such object
1004-2-7-s: no such object
1004-2-8-s: no such object
1004-2-1-dollarz: no such object
1004-2-2-dollarz: no such object
1004-2-3-dollarz: no such object
1004-2-4-dollarz: no such object
1004-2-5-dollarz: no such object
1004-2-6-dollarz: no such object
1004-2-7-dollarz: no such object
1004-2-8-dollarz: no such object
1004-3-1-off: no such object
1004-3-2-off: no such object
1004-3-3-off: no such object
1004-3-4-off: no such object
1004-3-5-off: no such object
1004-3-6-off: no such object
1004-3-7-off: no such object
1004-3-8-off: no such object
1004-3-1-s: no such object
1004-3-2-s: no such object
1004-3-3-s: no such object
1004-3-4-s: no such object
1004-3-5-s: no such object
1004-3-6-s: no such object
1004-3-7-s: no such object
1004-3-8-s: no such object
1004-3-1-dollarz: no such object
1004-3-2-dollarz: no such object
1004-3-3-dollarz: no such object
1004-3-4-dollarz: no such object
1004-3-5-dollarz: no such object
1004-3-6-dollarz: no such object
1004-3-7-dollarz: no such object
1004-3-8-dollarz: no such object
1004-3-1-off: no such object
1004-3-2-off: no such object
1004-3-3-off: no such object
1004-3-4-off: no such object
1004-3-5-off: no such object
1004-3-6-off: no such object
1004-3-7-off: no such object
1004-3-8-off: no such object
1004-3-1-s: no such object
1004-3-2-s: no such object
1004-3-3-s: no such object
1004-3-4-s: no such object
1004-3-5-s: no such object
1004-3-6-s: no such object
1004-3-7-s: no such object
1004-3-8-s: no such object
1004-3-1-dollarz: no such object
1004-3-2-dollarz: no such object
1004-3-3-dollarz: no such object
1004-3-4-dollarz: no such object
1004-3-5-dollarz: no such object
1004-3-6-dollarz: no such object
1004-3-7-dollarz: no such object
1004-3-8-dollarz: no such object
1004-4-1-off: no such object
1004-4-2-off: no such object
1004-4-3-off: no such object
1004-4-4-off: no such object
1004-4-5-off: no such object
1004-4-6-off: no such object
1004-4-7-off: no such object
1004-4-8-off: no such object
1004-4-1-s: no such object
1004-4-2-s: no such object
1004-4-3-s: no such object
1004-4-4-s: no such object
1004-4-5-s: no such object
1004-4-6-s: no such object
1004-4-7-s: no such object
1004-4-8-s: no such object
1004-4-1-dollarz: no such object
1004-4-2-dollarz: no such object
1004-4-3-dollarz: no such object
1004-4-4-dollarz: no such object
1004-4-5-dollarz: no such object
1004-4-6-dollarz: no such object
1004-4-7-dollarz: no such object
1004-4-8-dollarz: no such object
1004-4-1-off: no such object
1004-4-2-off: no such object
1004-4-3-off: no such object
1004-4-4-off: no such object
1004-4-5-off: no such object
1004-4-6-off: no such object
1004-4-7-off: no such object
1004-4-8-off: no such object
1004-4-1-s: no such object
1004-4-2-s: no such object
1004-4-3-s: no such object
1004-4-4-s: no such object
1004-4-5-s: no such object
1004-4-6-s: no such object
1004-4-7-s: no such object
1004-4-8-s: no such object
1004-4-1-dollarz: no such object
1004-4-2-dollarz: no such object
1004-4-3-dollarz: no such object
1004-4-4-dollarz: no such object
1004-4-5-dollarz: no such object
1004-4-6-dollarz: no such object
1004-4-7-dollarz: no such object
1004-4-8-dollarz: no such object
1004-5-1-off: no such object
1004-5-2-off: no such object
1004-5-3-off: no such object
1004-5-4-off: no such object
1004-5-5-off: no such object
1004-5-6-off: no such object
1004-5-7-off: no such object
1004-5-8-off: no such object
1004-5-1-s: no such object
1004-5-2-s: no such object
1004-5-3-s: no such object
1004-5-4-s: no such object
1004-5-5-s: no such object
1004-5-6-s: no such object
1004-5-7-s: no such object
1004-5-8-s: no such object
1004-5-1-dollarz: no such object
1004-5-2-dollarz: no such object
1004-5-3-dollarz: no such object
1004-5-4-dollarz: no such object
1004-5-5-dollarz: no such object
1004-5-6-dollarz: no such object
1004-5-7-dollarz: no such object
1004-5-8-dollarz: no such object
1004-5-1-off: no such object
1004-5-2-off: no such object
1004-5-3-off: no such object
1004-5-4-off: no such object
1004-5-5-off: no such object
1004-5-6-off: no such object
1004-5-7-off: no such object
1004-5-8-off: no such object
1004-5-1-s: no such object
1004-5-2-s: no such object
1004-5-3-s: no such object
1004-5-4-s: no such object
1004-5-5-s: no such object
1004-5-6-s: no such object
1004-5-7-s: no such object
1004-5-8-s: no such object
1004-5-1-dollarz: no such object
1004-5-2-dollarz: no such object
1004-5-3-dollarz: no such object
1004-5-4-dollarz: no such object
1004-5-5-dollarz: no such object
1004-5-6-dollarz: no such object
1004-5-7-dollarz: no such object
1004-5-8-dollarz: no such object
1004-6-1-off: no such object
1004-6-2-off: no such object
1004-6-3-off: no such object
1004-6-4-off: no such object
1004-6-5-off: no such object
1004-6-6-off: no such object
1004-6-7-off: no such object
1004-6-8-off: no such object
1004-6-1-s: no such object
1004-6-2-s: no such object
1004-6-3-s: no such object
1004-6-4-s: no such object
1004-6-5-s: no such object
1004-6-6-s: no such object
1004-6-7-s: no such object
1004-6-8-s: no such object
1004-6-1-dollarz: no such object
1004-6-2-dollarz: no such object
1004-6-3-dollarz: no such object
1004-6-4-dollarz: no such object
1004-6-5-dollarz: no such object
1004-6-6-dollarz: no such object
1004-6-7-dollarz: no such object
1004-6-8-dollarz: no such object
1004-6-1-off: no such object
1004-6-2-off: no such object
1004-6-3-off: no such object
1004-6-4-off: no such object
1004-6-5-off: no such object
1004-6-6-off: no such object
1004-6-7-off: no such object
1004-6-8-off: no such object
1004-6-1-s: no such object
1004-6-2-s: no such object
1004-6-3-s: no such object
1004-6-4-s: no such object
1004-6-5-s: no such object
1004-6-6-s: no such object
1004-6-7-s: no such object
1004-6-8-s: no such object
1004-6-1-dollarz: no such object
1004-6-2-dollarz: no such object
1004-6-3-dollarz: no such object
1004-6-4-dollarz: no such object
1004-6-5-dollarz: no such object
1004-6-6-dollarz: no such object
1004-6-7-dollarz: no such object
1004-6-8-dollarz: no such object
1004-7-1-off: no such object
1004-7-2-off: no such object
1004-7-3-off: no such object
1004-7-4-off: no such object
1004-7-5-off: no such object
1004-7-6-off: no such object
1004-7-7-off: no such object
1004-7-8-off: no such object
1004-7-1-s: no such object
1004-7-2-s: no such object
1004-7-3-s: no such object
1004-7-4-s: no such object
1004-7-5-s: no such object
1004-7-6-s: no such object
1004-7-7-s: no such object
1004-7-8-s: no such object
1004-7-1-dollarz: no such object
1004-7-2-dollarz: no such object
1004-7-3-dollarz: no such object
1004-7-4-dollarz: no such object
1004-7-5-dollarz: no such object
1004-7-6-dollarz: no such object
1004-7-7-dollarz: no such object
1004-7-8-dollarz: no such object
1004-7-1-off: no such object
1004-7-2-off: no such object
1004-7-3-off: no such object
1004-7-4-off: no such object
1004-7-5-off: no such object
1004-7-6-off: no such object
1004-7-7-off: no such object
1004-7-8-off: no such object
1004-7-1-s: no such object
1004-7-2-s: no such object
1004-7-3-s: no such object
1004-7-4-s: no such object
1004-7-5-s: no such object
1004-7-6-s: no such object
1004-7-7-s: no such object
1004-7-8-s: no such object
1004-7-1-dollarz: no such object
1004-7-2-dollarz: no such object
1004-7-3-dollarz: no such object
1004-7-4-dollarz: no such object
1004-7-5-dollarz: no such object
1004-7-6-dollarz: no such object
1004-7-7-dollarz: no such object
1004-7-8-dollarz: no such object
1004-8-1-off: no such object
1004-8-2-off: no such object
1004-8-3-off: no such object
1004-8-4-off: no such object
1004-8-5-off: no such object
1004-8-6-off: no such object
1004-8-7-off: no such object
1004-8-8-off: no such object
1004-8-1-s: no such object
1004-8-2-s: no such object
1004-8-3-s: no such object
1004-8-4-s: no such object
1004-8-5-s: no such object
1004-8-6-s: no such object
1004-8-7-s: no such object
1004-8-8-s: no such object
1004-8-1-dollarz: no such object
1004-8-2-dollarz: no such object
1004-8-3-dollarz: no such object
1004-8-4-dollarz: no such object
1004-8-5-dollarz: no such object
1004-8-6-dollarz: no such object
1004-8-7-dollarz: no such object
1004-8-8-dollarz: no such object
1004-8-1-off: no such object
1004-8-2-off: no such object
1004-8-3-off: no such object
1004-8-4-off: no such object
1004-8-5-off: no such object
1004-8-6-off: no such object
1004-8-7-off: no such object
1004-8-8-off: no such object
1004-8-1-s: no such object
1004-8-2-s: no such object
1004-8-3-s: no such object
1004-8-4-s: no such object
1004-8-5-s: no such object
1004-8-6-s: no such object
1004-8-7-s: no such object
1004-8-8-s: no such object
1004-8-1-dollarz: no such object
1004-8-2-dollarz: no such object
1004-8-3-dollarz: no such object
1004-8-4-dollarz: no such object
1004-8-5-dollarz: no such object
1004-8-6-dollarz: no such object
1004-8-7-dollarz: no such object
1004-8-8-dollarz: no such object
`

**Comment by LGoodacre** [comment]
There seem to be two parts to this error, one of which I can replicate and the other which I can't.

`array: couldn't find named array '1003-IDshare' text sequence: line number 0 out of range text sequence: line number 0 out of range`

This happens when you create an instance of [control] before any instance of [context] has been created, since [control] is looking for some shared arrays which only appear with [context]. It's a bit annoying, but since [control] is useless without [context], it's not a major problem.

As for the broken objects, I can't replicate this error on Windows or Linux, but it seems to be something to do with path declarations. Have you added the main Context folder to the search paths? (Edit-->Preferences-->Path-->New). If you have, then I'm stumped as to what it might be...

**Comment by aclaiman** [comment]
The 1st part is solved

The broken objects are still there. I did declare context path,,,

But I dont find those objects anywhere. In witch folder should I look?

**Comment by LGoodacre** [comment]
Could you send me a screenshot? Right click on [control] and open it up and show me what it looks like.

**Comment by aclaiman** [comment]
Sure!
![control_error](https://user-images.githubusercontent.com/37425769/41654953-71f25144-7461-11e8-9e78-0af4e0dd1f5f.jpg)
![control_error2](https://user-images.githubusercontent.com/37425769/41655186-7bb82d06-7462-11e8-8568-799c9c1bf72d.jpg)

**Comment by LGoodacre** [comment]
Can you right-click on any of those elongated rectangles that take up most of the GUI, select 'open' and send me another screenshot?
For reference, this is what I mean (although it will obviously look a little different on your machine).

![control](https://user-images.githubusercontent.com/22167643/41658204-4bca5352-74b3-11e8-8ff6-12791397342f.png)

**Comment by LGoodacre** [comment]
And if you can see those bang objects inside p3.pd, right click again, open it up and send another screenshot!
![control2](https://user-images.githubusercontent.com/22167643/41658369-c703641e-74b3-11e8-9908-32e49895b879.png)

**Comment by aclaiman** [comment]
![control_error3](https://user-images.githubusercontent.com/37425769/41662988-c052ad18-7478-11e8-88cf-168fd62bf590.jpg)
I think there is the problem.
NEW!
There is a pp object in another library that is have installed called iemlib so p3 loads those objects instade of yours...
I´m goingo to rename pp and see what happends.
I´ll keep you posted.
Thanks.

**Comment by LGoodacre** [comment]
Yup, that's the problem! Thanks for identifying it. It's a shame that I didn't know about this earlier, as it might affect other users as well. I'll change the names on the git repo. If you want, you can download it from there, or you can just change them yourself.

**Comment by LGoodacre** [comment]
So I renamed pp.pd as pcell.pd and updated p3.pd accordingly. You can download the relevant files here, and delete pp.pd: https://github.com/LGoodacre/context-sequencer/tree/master/ctxfiles
